In [1]:
from starccato_flow.training.trainer_flow_matching_multi import FlowMatchingTrainerMulti
from starccato_flow.supernovae.supernovae import Supernovae
from starccato_flow.utils.defaults import TEN_KPC
import numpy as np

MPS device found


/Users/tarineccleston/Desktop/starccato/starccato-flow/.venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### Configs

In [2]:
font_family = "serif"
font_name = "Times New Roman"

In [3]:
# supernovae_simple = Supernovae(rotation_offset=np.deg2rad(60.0))
supernovae_complex = Supernovae(locations_file='../../exploded_supernovae_t100_sf5.csv', rotation_offset=np.deg2rad(60.0))

✓ Loaded 1934076 supernova locations from ../../exploded_supernovae_t100_sf5.csv


### Simple Galactic Supernovae Distribution

In [4]:
# supernovae_simple.plot_galactic_distribution(
#     fname_xy="../2025-Statistics-Masters-Thesis/figures/supernovae/supernovae_galactic_distribution_simple.png",
#     font_family=font_family,
#     font_name=font_name
# )

### Complex Galactic Supernovae Distribution (what we end up using)

In [5]:
supernovae_complex.plot_galactic_distribution(
    fname_xy="../2025-Statistics-Masters-Thesis/figures/supernovae/supernovae_galactic_distribution_complex.png",
    font_family=font_family,
    font_name=font_name,
    transparent=False
);

### Curriculum Learning -- Sampled Supernovae

In [ ]:
supernovae_complex.sample_supernovae_for_epoch(
    epoch=0,
    n_samples=20000,
    num_epochs=256,
    exponential=True,
    validation=False,
    fname="../2025-Statistics-Masters-Thesis/figures/supernovae/first_sampled_supernovae_galactic_distribution_complex.png",
    font_family=font_family,
    font_name=font_name
)

supernovae_complex.sample_supernovae_for_epoch(
    epoch=256,
    n_samples=20000,
    num_epochs=256,
    exponential=True,
    validation=False,
    fname="../2025-Statistics-Masters-Thesis/figures/supernovae/final_sampled_supernovae_galactic_distribution_complex.png",
    font_family=font_family,
    font_name=font_name
)

(array([-1.4012966 , -1.49783133,  2.5276194 , ..., -2.10965965,
         1.46170745,  2.48934937]),
 array([-1.14073897, -0.82309526, -0.59532847, ..., -0.23902059,
         0.43256504, -0.61309848]),
 array([0.92205988, 0.93022422, 0.58394302, ..., 0.79659367, 0.79289737,
        0.59256866]))

In [9]:
import subprocess

# Add all files
subprocess.run(["git", "pull"], cwd="../2025-Statistics-Masters-Thesis")
subprocess.run(["git", "add", "."], cwd="../2025-Statistics-Masters-Thesis")
# Commit
subprocess.run(["git", "commit", "-m", "Update Plots"], cwd="../2025-Statistics-Masters-Thesis")
# Push
subprocess.run(["git", "push"], cwd="../2025-Statistics-Masters-Thesis")

From github.com:the-tarin/2025-Statistics-Masters-Thesis
   0c5f59d..e0ac720  main       -> origin/main


Updating 0c5f59d..e0ac720
Fast-forward
 dissertation.tex                                   |  89 +++++++++++++--------
 figures/astronomy/gw_signal_distribution.png       | Bin 41749 -> 0 bytes
 figures/astronomy/gw_signals_sample_16_signals.png | Bin 127119 -> 0 bytes
 3 files changed, 56 insertions(+), 33 deletions(-)
 delete mode 100644 figures/astronomy/gw_signal_distribution.png
 delete mode 100644 figures/astronomy/gw_signals_sample_16_signals.png
[main f27bd5c] Update Plots
 3 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 figures/supernovae/final_sampled_supernovae_galactic_distribution_complex.png
 create mode 100644 figures/supernovae/first_sampled_supernovae_galactic_distribution_complex.png
 delete mode 100644 figures/supernovae/sampled_supernovae_galactic_distribution_complex.png


To github.com:the-tarin/2025-Statistics-Masters-Thesis.git
   e0ac720..f27bd5c  main -> main


CompletedProcess(args=['git', 'push'], returncode=0)