In [1]:
from starccato_flow.training.trainer_flow_matching_multi import FlowMatchingTrainerMulti
from starccato_flow.supernovae.supernovae import Supernovae
from starccato_flow.utils.defaults import TEN_KPC
import numpy as np

MPS device found


/Users/tarineccleston/Desktop/starccato/starccato-flow/.venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
font_family = "sans-serif"
font_name = "avenir"

In [3]:
supernovae_complex = Supernovae(locations_file='../../data/supernovae/exploded_supernovae_t100_sf5.csv', rotation_offset=np.deg2rad(0.0))

✓ Loaded 1934076 supernova locations from ../../data/supernovae/exploded_supernovae_t100_sf5.csv


In [4]:
supernovae_complex.sample_supernovae_for_epoch(
    epoch=1,
    n_samples=18000,
    num_epochs=256,
    exponential=True,
    fname="../../poster-presentation/epoch_1.png",
    font_family=font_family,
    font_name=font_name
)

supernovae_complex.sample_supernovae_for_epoch(
    epoch=128,
    n_samples=18000,
    num_epochs=256,
    exponential=True,
    fname="../../poster-presentation/epoch_128.png",
    font_family=font_family,
    font_name=font_name
)

supernovae_complex.sample_supernovae_for_epoch(
    epoch=256,
    n_samples=18000,
    num_epochs=256,
    exponential=True,
    fname="../../poster-presentation/epoch_256.png",
    font_family=font_family,
    font_name=font_name
)

(array([4.15365965, 4.7215519 , 5.17602043, ..., 4.34649714, 1.47061267,
        4.92457665]),
 array([-0.91460804, -0.39898064,  0.4136054 , ..., -0.85382473,
         0.55492818, -0.00778793]),
 array([9.45929773, 9.2534056 , 9.93930446, ..., 8.37096436, 8.79797545,
        9.5554043 ]))